### ISSUE TITLE
Fail to download subset 'tiny'

### ISSUE THREAD

**Issue by Hermera** [EPFL-VILAB/omnidata#61]
I am following the instructions of downloading data. The following command works for me.
```
omnitools.download rgb depth_euclidean mask_valid \
    --components taskonomy replica \
    --subset debug \
    --dest ./omnidata_starter_dataset/ \
    --name YOUR_NAME --email YOUR_EMAIL --agree_all
```

However, when I change `--subset debug` to `--subset tiny`, I got this error:
```
03/31 16:58:21 [NOTICE] IPv4 RPC: listening on TCP port 6800
['point_info', 'rgb', 'depth_euclidean', 'mask_valid', 'fragments']                                                                                                                                 
Traceback (most recent call last):
  File "/n/fs/pvl-curve/mamba/envs/omnidata/bin/omnitools.download", line 8, in <module>
    sys.exit(download())
             ^^^^^^^^^^
  File "/n/fs/pvl-curve/mamba/envs/omnidata/lib/python3.12/site-packages/fastcore/script.py", line 119, in _f
    return tfunc(**merge(args, args_from_prog(func, xtra)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/fs/pvl-curve/mamba/envs/omnidata/lib/python3.12/site-packages/omnidata_tools/dataset/download.py", line 267, in download
    models = filter_models(models, domains, subset, split, components, 
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/n/fs/pvl-curve/mamba/envs/omnidata/lib/python3.12/site-packages/omnidata_tools/dataset/download.py", line 119, in filter_models
    and (subset == 'all' or component_to_subset[m.component_name.lower()] is None or m.model_name in component_to_subset[m.component_name.lower()][subset]) 
                                                                                                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
KeyError: 'tiny'
                                                                                                                                                                                                    
03/31 16:58:26 [NOTICE] Shutdown sequence commencing... Press Ctrl-C again for emergency shutdown.
```

Anyone know how to fix this issue?

**Comment by alexsax** [comment]
Replica does not have an official tiny split. The error message could be
more informative here, but only the Taskonomy has a “tiny” subset
